DROP TABLE IF EXISTS MEDICARE_PROVIDERS;
DROP TABLE IF EXISTS ZIP_CODE;

--Zip Code Table--
CREATE TABLE ZIP_CODE (
  ZIP text not null,
  CITY text,
  STATE text,
  LATITUDE text,
  LONGITUDE text,
  PRIMARY KEY (ZIP)
);

--Medicare Providers Table--
CREATE TABLE MEDICARE_PROVIDERS (
  NPI text not null,
  NPPES_ENTITY_CODE text,
  NPPES_PROVIDER_ZIP text not null references ZIP_CODE(ZIP),
  NPPES_PROVIDER_COUNTRY text,
  PROVIDER_TYPE text,
  TOTAL_UNIQUE_BENES text,
  TOTAL_MEDICARE_PAYMENT_AMT money,
  BENEFICIARY_CC_DIAB_PERCENT text,
  PRIMARY KEY (NPI)
);

SELECT COUNT(DISTINCT MEDICARE_PROVIDERS.PROVIDER_TYPE), ZIP_CODE.STATE
FROM MEDICARE_PROVIDERS 
INNER JOIN ZIP_CODE ON MEDICARE_PROVIDERS.nppes_provider_zip=ZIP_CODE.ZIP
WHERE NPPES_ENTITY_CODE = 'I' AND NPPES_PROVIDER_COUNTRY = 'US'
GROUP BY ZIP_CODE.STATE

SELECT ROUND(AVG(MEDICARE_PROVIDERS.TOTAL_MEDICARE_PAYMENT_AMT), 2), ZIP_CODE.STATE
FROM MEDICARE_PROVIDERS 
INNER JOIN ZIP_CODE ON MEDICARE_PROVIDERS.nppes_provider_zip=ZIP_CODE.ZIP
WHERE NPPES_ENTITY_CODE = 'I' AND NPPES_PROVIDER_COUNTRY = 'US'
GROUP BY ZIP_CODE.STATE