const PROVIDER_COUNT_BY_STATE = "SELECT COUNT(DISTINCT MEDICARE_PROVIDERS.PROVIDER_TYPE), ZIP_CODE.STATE " +
"FROM MEDICARE_PROVIDERS " + 
"INNER JOIN ZIP_CODE ON MEDICARE_PROVIDERS.nppes_provider_zip=ZIP_CODE.ZIP " + 
"WHERE NPPES_ENTITY_CODE = 'I' AND NPPES_PROVIDER_COUNTRY = 'US' " +
"GROUP BY ZIP_CODE.STATE";

module.exports = {PROVIDER_COUNT_BY_STATE};